### ISSUE TITLE
Status options don't appear at all on Firefox, Estimated cost spinner doesn't appear on IE and Edge

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-ideas#22]
It appears that the UI when creating / editing an Idea appears differently on different browsers:

On Firefox 65:

1. when creating a new Idea the options from the Status list don't appear at all
2. the spinner from Estimated cost appears all the time as oppose to only appearing when the mouse is hovered over the Estimated cost field on Chrome 72

On IE 11 and Edge 18:

1. the spinner from the Estimated cost field doesn't appear at all

Environment: Windows 10, XWiki 10.11.2 MySQL 5.7 and Edge 18 / Chrome 72 / Firefox 65 / IE 11, Ideas Application (Pro) 1.11.1

![firefoxstatus](https://user-images.githubusercontent.com/40691112/52479014-df788700-2baf-11e9-97d1-8c01b4cee116.jpg)
![edge18](https://user-images.githubusercontent.com/40691112/52479071-0d5dcb80-2bb0-11e9-879d-21498ff1ac0d.jpg)

**Comment by oanalavinia** [comment]
Regarding Estimated cost spinner, the problem is that type="number" is not fully supported on IE https://caniuse.com/#search=number .
The field is still verifying if the input is numeric. But there is no warning regarding this, just that the value is not saved and you have to retry. The spinner would have clarify the fact that there should be a number and besides this I don't think is very usefull.
My question is if we should find a workaroud for having the spinner on IE or it would also be usefull to have some warnings or a hint on the input instead?

**Comment by oanalavinia** [comment]
There is also this issue that is related https://github.com/xwikisas/application-ideas/issues/6

**Comment by oanalavinia** [comment]
I have discussed with Marius and for the Estimated cost spinner it shouldn't be made a change, since the functionalities of that field are still applicable, even if you cannot see the arrows.
